In [2]:
#get method 
import pandas as pd
l = {'Name':['sonu','aamir','atau'],
     'age':[24,25,78]    
}
df = pd.DataFrame(l)
df.set_index('age',inplace=True)
df['Name'].get([25,78])

age
25    aamir
78     atau
Name: Name, dtype: object

In [32]:
#get method and overwrite to series 
import pandas as pd
path = r"C:\Users\mmohdat\Downloads\decoder-export-results-07b1bb83-0f08-4d73-be1e-81cfdb8150e5.csv"
df = pd.read_csv(path,usecols=['gl_product_group_type']).squeeze('columns')

In [33]:
df.get([1,2])

1                   { value:gl_home }
2     { value:gl_mobile_electronics }
Name: gl_product_group_type, dtype: object

In [34]:
df[1] = 'gl_home'

In [35]:
df[145] = 'gl_elec'

In [36]:
df[[1,2,3]]= ['home','electronics','wireless']

In [37]:
df

0        { value:gl_lawn_and_garden }
1                                home
2                         electronics
3                            wireless
4                { value:gl_apparel }
5                 { value:gl_sports }
6               { value:gl_wireless }
7                { value:gl_kitchen }
8                     { value:gl_pc }
9            { value:gl_electronics }
10               { value:gl_kitchen }
11             { value:gl_furniture }
12       { value:gl_lawn_and_garden }
13                { value:gl_sports }
14              { value:gl_wireless }
15                    { value:gl_pc }
16                 { value:gl_tools }
17              { value:gl_wireless }
18               { value:gl_kitchen }
19                  { value:gl_home }
20               { value:gl_kitchen }
21              { value:gl_outdoors }
22              { value:gl_wireless }
23      { value:gl_home_improvement }
24             { value:gl_furniture }
25                  { value:gl_home }
26       { value:gl_lawn_and_garden }
27                    { value:gl_pc }
28                { value:gl_sports }
29               { value:gl_apparel }
30              { value:gl_outdoors }
31        { value:gl_office_product }
32      { value:gl_home_improvement }
33                    { value:gl_pc }
34              { value:gl_outdoors }
35             { value:gl_furniture }
36             { value:gl_furniture }
37                { value:gl_beauty }
38               { value:gl_kitchen }
39             { value:gl_furniture }
40                 { value:gl_tools }
41           { value:gl_electronics }
42           { value:gl_electronics }
43               { value:gl_kitchen }
44               { value:gl_kitchen }
145                           gl_elec
Name: gl_product_group_type, dtype: object

In [38]:
#OVERWRITE BY INDEX NAME 
df = pd.read_csv(path,index_col='ASIN').squeeze('columns')

In [42]:
df['B0BH9DPWZ3'] = 'Test'

In [43]:
df

,item_name,gl_product_group_type,B0BH9DPWZ3
ASIN,,,
B0BH9DPWZ3,"{ language_tag:es_MX, value:""Kingsman | Hidro...",{ value:gl_lawn_and_garden },Test
B0C54NP3QN,"{ language_tag:es_MX, value:""REAL TEXTIL - Ed...",{ value:gl_home },Test
B0778N5X16,"{ language_tag:es_MX, value:""Baofeng BF-888s ...",{ value:gl_mobile_electronics },Test
B09WX1C7G5,"{ language_tag:es_MX, value:""HONOR X8 Celular...",{ value:gl_wireless },Test
B09WTWLXD3,"{ language_tag:es_MX, value:""MARIA BELA DT / ...",{ value:gl_apparel },Test
B0BVQ1X415,"{ language_tag:es_MX, value:""Trampolín Para N...",{ value:gl_sports },Test
B07XWGWPH5,"{ language_tag:es_MX, value:""OnePlus Nord N20...",{ value:gl_wireless },Test
B09BZVQNTC,"{ language_tag:es_MX, value:""Freidora de aire...",{ value:gl_kitchen },Test
B0BW3S2S27,"{ language_tag:es_MX, value:""2023 CHUWI HiPad...",{ value:gl_pc },Test
B09HWRND3C,"{ language_tag:es_MX, value:""BOMGE uhf - Micr...",{ value:gl_electronics },Test
B00Y7Z22M8,"{ language_tag:es_MX, value:""Juego de sartene...",{ value:gl_kitchen },Test
B0BX1T64JM,"{ language_tag:es_MX, value:""GAON. Cuna Colec...",{ value:gl_furniture },Test
B07DFCJ1H2,"{ language_tag:es_MX, value:""BLACK+DECKER Hid...",{ value:gl_lawn_and_garden },Test
B0BMP78G9R,"{ language_tag:es_MX, value:""UrbanFit Pro Min...",{ value:gl_sports },Test
B0BDJ3ZJSS,"{ language_tag:es_MX, value:""Apple iPhone 14 ...",{ value:gl_wireless },Test
B0BSRBDQ25,"{ language_tag:es_MX, value:""Lenovo Tab M10 G...",{ value:gl_pc },Test
B00F2J9LPO,"{ language_tag:es_MX, value:""STANLEY Mochila ...",{ value:gl_tools },Test
B08DVHL2DV,"{ language_tag:es_MX, value:""Xiaomi Redmi 9C ...",{ value:gl_wireless },Test
B0C7HKPP63,"{ language_tag:es_MX, value:""Maquina para Hac...",{ value:gl_kitchen },Test
B0BCH7JV3J,"{ language_tag:es_MX, value:""ShopMall Muro Ve...",{ value:gl_home },Test
B0B1JRQXVP,"{ language_tag:es_MX, value:""T-fal Plancha Ea...",{ value:gl_kitchen },Test
B0C6LT561C,"{ language_tag:es_MX, value:""KUBOR Bicicleta ...",{ value:gl_outdoors },Test
B07VM7R3KT,"{ language_tag:es_MX, value:""ZTE Smartphone B...",{ value:gl_wireless },Test
B07R7RDL75,"{ language_tag:es_MX, value:""Compresora Oakla...",{ value:gl_home_improvement },Test
B01M1H039I,"{ language_tag:es_MX, value:""Bio Mattress Col...",{ value:gl_furniture },Test
B0BKGZGR84,"{ language_tag:es_MX, value:""KINGSMAN | Caja ...",{ value:gl_home },Test
B0987BDT45,"{ language_tag:es_MX, value:""Glückluz 2 en 1 ...",{ value:gl_lawn_and_garden },Test
B0BTV1P944,"{ language_tag:es_MX, value:""H P Laptop 245 G...",{ value:gl_pc },Test
B0BMQWFWJL,"{ language_tag:es_MX, value:""UrbanFit Pro Ban...",{ value:gl_sports },Test
B0C6C8HP1R,"{ language_tag:es_MX, value:""Yim Sports Kit d...",{ value:gl_apparel },Test
B09Z79NY3K,"{ language_tag:es_MX, value:""Xtreme Life Bici...",{ value:gl_outdoors },Test
B0BT3Y3WS4,"{ language_tag:es_MX, value:""Scribe Fotobond ...",{ value:gl_office_product },Test
B09WJPKJZC,"{ language_tag:es_MX, value:""KINGSMAN | Gener...",{ value:gl_home_improvement },Test
B0BVDSWGMC,"{ language_tag:es_MX, value:""Lenovo Laptop Id...",{ value:gl_pc },Test
B0CBNM3HDX,"{ language_tag:es_MX, value:""Black Panther Bi...",{ value:gl_outdoors },Test
B0BVPKGHNL,"{ language_tag:es_MX, value:""GAON. 2 Sillas P...",{ value:gl_furniture },Test
B07NK3GGM8,"{ language_tag:es_MX, value:""Madesa Mueble pa...",{ value:gl_furniture },Test
B09PWX5LTH,"{ language_tag:es_MX, value:""Tratamiento para...",{ value:gl_beauty },Test
B01N022IKU,"{ language_tag:es_MX, value:""Hamilton Beach 6...",{ value:gl_kitchen },Test
B0BTDTSVNK,"{ language_tag:es_MX, value:""GAON. Silla Eame...",{ value:gl_furniture },Test
B0BDMXWKLT,"{ language_tag:es_MX, value:""Sierra Ingletead...",{ value:gl_tools },Test
B0B8V8XTF7,"{ language_tag:es_MX, value:""Realme TechLife ...",{ value:gl_electronics },Test
B0BVYLXV28,"{ language_tag:es_MX, value:""realme Buds Air ...",{ value:gl_electronics },Test
B09LK4QGYJ,"{ language_tag:es_MX, value:""Luminarc 307-525...",{ value:gl_kitchen },Test
B0BRR112XX,"{ language_tag:es_MX, value:""Bluelander Vaso ...",{ value:gl_kitchen },Test

In [15]:
import pandas as pd 

df = pd.read_csv('nba.csv')
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [16]:
selected_columns = ['Name','Age','Weight','College']
df[selected_columns].head(2)
df.insert(loc=1,column='Last Name',value='Ansari')

In [17]:
df.insert(loc=4,column='Location',value='Delhi')
df

,Name,Last Name,Team,Number,Location,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Ansari,Boston Celtics,0.0,Delhi,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Ansari,Boston Celtics,99.0,Delhi,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Ansari,Boston Celtics,30.0,Delhi,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Ansari,Boston Celtics,28.0,Delhi,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Ansari,Boston Celtics,8.0,Delhi,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Ansari,Utah Jazz,8.0,Delhi,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Ansari,Utah Jazz,25.0,Delhi,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Ansari,Utah Jazz,21.0,Delhi,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Ansari,Utah Jazz,24.0,Delhi,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,Ansari,NaN,NaN,Delhi,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df['age in decade'] = df['Age']-10
df.columns
df.head(2)

,Name,Last Name,Team,Number,Location,Position,Age,Height,Weight,College,Salary,age in decade
0,Avery Bradley,Ansari,Boston Celtics,0.0,Delhi,PG,25.0,6-2,180.0,Texas,7730337.0,15.0
1,Jae Crowder,Ansari,Boston Celtics,99.0,Delhi,SF,25.0,6-6,235.0,Marquette,6796117.0,15.0

In [28]:
df.sort_values(by=['Name','Age'],ascending=['False','True'])

ValueError: For argument "ascending" expected type bool, received type str.

In [55]:
path = r'C:\Users\mmohdat\Downloads\EU3_Softline_WBR_Week_35.xlsx'
df = pd.read_excel(path)
df.dropna(how='all')
# df = df['Def']
df.columns

Index(['concat', 'cluster', 'team', 'Local', 'UserID', 'manufacturer_name',
       'manufacturer_code', 'service_type', 'Prioritization', 'idq_score_v2',
       'idq_grade', 'PAC', 'relevant_attributes_missing', 'RAC_type',
       'product_family', 'product_type', 'gl_name', 'asin', 'parent_asin',
       'defect_type', 'creation_date', 'brand_name', 'has_vtc_agreement',
       'vendor_id', 'Winston_case_id', 'action', 'Content', 'value', 'Reasons',
       'sub_action', 'platform', 'publish_date', 'project_title', 'Link',
       'week_no', 'Upload_link', 'Comments', 'notes', 'Automation',
       'paragon_id', 'year', 'is_bc', 'clientWorkItemStatus', 'OPT-IN-OUT'],
      dtype='object')

In [64]:
from pandas import ExcelWriter
df = df[(df['defect_type'] != 'Aplus') & (df['action']=='Touched')]
df = df['UserID'].sort_values()
# print(df)
count = df['UserID'].value_counts(ascending=False)
print(count)
# df.to_excel('test1.xlsx',index=False)
# with ExcelWriter('Output.xlsx') as writer:
#     # Write the filtered DataFrame to the first sheet
#     df.to_excel(writer, sheet_name='FilteredData', index=False)
    
#     # Write the count of 'UserID' values to the second sheet
#     count.to_excel(writer, sheet_name='UserIDCount', index=False)

KeyError: 'defect_type'

In [43]:
df['Count'] = df.groupby('UserID')['UserID'].transform('count')
df['User_IDs'] = df['UserID']
df['Count']

0        2903
1        2903
2        2903
3        2903
4        2903
         ...
47441    2384
47442    2384
47443    2384
47444    2384
47445    2384
Name: Count, Length: 25559, dtype: int64

In [28]:
import pandas as pd
p = r'C:\Users\mmohdat\Documents\test_done.xlsx'
df = pd.read_excel(p)
df.sort_values('employeeID',inplace=True)

In [31]:
mask = ~df['employeeID'].duplicated(keep=False)
df[mask]

Empty DataFrame
Columns: [employeeID, MP, Date, Value, taskName, subtaskName, mpName, glName, processedDay (mm/dd/yy), productionType, IDQ, Aplus, Final HERA]
Index: []

In [29]:
df

,employeeID,MP,Date,Value,taskName,subtaskName,mpName,glName,processedDay (mm/dd/yy),productionType,IDQ,Aplus,Final HERA
0,aayushiw,SL,2023-08-31,NaN,CIDQ,Un Structured Attribute,FR,Home Improvement,2023-08-31,Productive,4.540741,0.0,4.540741
1,aayushiw,SL,2023-08-30,NaN,CIDQ,Un Structured Attribute,FR,Home Improvement,2023-08-30,Productive,4.540741,0.0,4.540741
2,aayushiw,SL,2023-09-02,AVB,CIDQ,Un Structured Attribute,FR,Home Improvement,2023-09-02,None Productive,4.540741,0.0,4.540741
3,aayushiw,SL,2023-08-29,OL,CIDQ,Un Structured Attribute,FR,Home Improvement,2023-08-29,Productive,4.540741,0.0,4.540741
4,aayushiw,SL,2023-09-01,NaN,CIDQ,Un Structured Attribute,FR,Home Improvement,2023-09-01,Productive,4.540741,0.0,4.540741
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,yogaredd,SL,2023-09-02,AVB,CIDQ,Un Structured Attribute,UK,Apparel,2023-09-02,None Productive,11.407407,0.0,11.407407
121,yogaredd,SL,2023-08-28,NaN,CIDQ,Un Structured Attribute,UK,Apparel,2023-08-28,Productive,11.407407,0.0,11.407407
122,yogaredd,SL,2023-09-01,NaN,CIDQ,Un Structured Attribute,UK,Apparel,2023-09-01,Productive,11.407407,0.0,11.407407
123,yogaredd,SL,2023-08-30,NaN,CIDQ,Un Structured Attribute,UK,Apparel,2023-08-30,Productive,11.407407,0.0,11.407407
125,yogaredd,SL,2023-08-29,NaN,CIDQ,Un Structured Attribute,UK,Apparel,2023-08-29,Productive,11.407407,0.0,11.407407

In [8]:
import pandas as pd
import os
directory = r'C:\Users\mmohdat\Documents\ARTS\July-23\Vulcan ISM - Outages - [EU4] 2043\Export file'
def get_latest_file_df(mp):
    if os.path.exists(directory):
        files = os.listdir(directory)
        if len(files) > 0:
            # Sort the files by modification time (most recent first)
            sorted_files = sorted(files, key=lambda x: os.path.getmtime(os.path.join(directory, x)), reverse=True)

            latest_file = sorted_files[0]
            print("Latest file:", latest_file)
            df = pd.read_csv(directory + '\\' + latest_file)

            l = []

            for i in range(len(df)):
                l.append(mp)

            df['MP'] = l

            df.to_csv(os.getcwd() + "\\Export file\\" + latest_file, index=False)
            print(df)
        else:
            print("No files found in the directory.")
    else:
        print("Directory does not exist.")

In [10]:
get_latest_file_df('DE')

No files found in the directory.